mustafa89de/nearly

package-lock.json, package.json, src/backend/configuration/config.js, src/backend/services/JWTService.js, src/backend/services/UserService.js
token generation implemented, tested with postman
=> Mi 89 generate jwt

src/backend/app.js, src/backend/controller/AuthenticationController.js, src/backend/controller/index.js, src/backend/models/User.js, src/backend/passport.js, src/backend/services/UserService.js
added passport.js implementation and secure endpoint: uses jwt strategy to authenticate token in authorization header, responds with secret if succesfull
=> Mi 93 auth controller secure test route

src/backend/passport.js
implemented strategy to authenticate email and password
passport.js has to be top level in backend, configures passport middleware
=> Mi 91 email pw authentication

src/backend/controller/AuthenticationController.js, src/backend/controller/index.js, src/backend/passport.js
added passport.js implementation and login endpoint: uses local strategy to authenticate email and password, issues token if successful
=> Mi 92 auth controller login route

.babelrc, package-lock.json, package.json, src/backend/controller/EventController.js, src/backend/controller/EventController.test.js, src/backend/controller/UserController.test.js, src/backend/controller/index.js, src/backend/models/Event.js, src/backend/repositories/EventRepository.js, src/backend/repositories/EventRepository.test.js, src/backend/services/DBService.js, src/frontend/components/Button.vue, src/frontend/components/Icon.vue, src/frontend/components/TextInput.vue, src/frontend/pages/RegistrationPage.test.js, src/frontend/pages/RegistrationPage.vue, src/jestMock.js, webpack.config.js
* Add Event model, 
* implement UNSECURED create event endpoint (secured will follow if login ist merged)
* add tests for everything new
* improve controller test
* reactivate and fix failing tests
** updated babel
** remove webpack alias
** add jest mocks for svgs
** disabled first test
MI-13
=> MI-13: Event Model + Endpoint + Tests

src/backend/controller/EventController.js, src/backend/models/Event.js, src/backend/repositories/EventRepository.js, src/frontend/components/TextInput.vue, src/frontend/pages/CreateEventPage.test.js, src/frontend/pages/CreateEventPage.vue, src/frontend/services/EventService.js, src/frontend/services/EventService.test.js
transformed location in event model to lat and long
adjust frontend
MI-13
=> Event.Location -> Event.Latitude & Event.Longitude

src/frontend/App.vue, src/frontend/assets/variables.scss, src/frontend/components/Button.vue, src/frontend/components/Icon.vue, src/frontend/components/TextInput.vue, src/frontend/pages/CreateEventPage.vue, src/frontend/pages/LoginPage.vue, src/frontend/pages/RegistrationPage.vue
- add designs for create event page
- refactored css variables (as discussed with bean)
- pass through click for button component
- switch show hide password icons
- fix bg color style orders
- fix paddings and spaces of input component
MI-21
=> Create Event Designs + some css fixes

src/backend/controller/EventController.js, src/backend/repositories/EventRepository.js
Added Endpoint for Eventdetails Request on api/event/:eid, 
test with postman worked fine, 
endpoint automated test will follow after review.
=> ADD: Endpoint for getting full eventdetails (Document) by ID

src/backend/controller/EventController.js, src/backend/repositories/EventRepository.js, src/frontend/index.js, src/frontend/pages/EventDetailPage.vue, src/frontend/services/EventService.js
Added initial EventDetailPage and fetch functions to get Eventdetails from Backend
Page styling will follow soon
=> Mi 121 124/initial event detail page and fetching

src/frontend/pages/CreateEventPage.vue
=> fixed datetime bug

src/backend/controller/EventController.js, src/backend/models/Event.js, src/backend/repositories/EventRepository.js, src/backend/services/MapService.js
- added route to GET events in area
- updated mongoose model to include location as geoJSON
- updated route to POST events to fit updated model
- added query to get events in area to event repo
- added MapService/createMissingBounds function to calculate bounds missing in request made to GET events
=> Mi 116 endpoint get events

src/backend/controller/EventController.js, src/frontend/components/Map.vue, src/frontend/pages/EventOverviewPage.vue, src/frontend/services/EventService.js
=> fetch endpint, fix data type bug for bounds

src/frontend/App.vue, src/frontend/assets/icons/home.svg, src/frontend/assets/icons/place-add.svg, src/frontend/assets/variables.scss, src/frontend/components/Icon.vue, src/frontend/components/NavBar.vue, src/frontend/pages/EventOverviewPage.vue, src/frontend/pages/HomePage.vue
=> Add nav, show only if loggedIn

src/frontend/components/EventListItem.vue, src/frontend/components/HorizontalEventList.vue, src/frontend/components/Map.vue, src/frontend/components/NavBar.vue, src/frontend/constants.js, src/frontend/pages/EventOverviewPage.vue, src/frontend/services/LocationService.js
add async initial position detection and improve fetch flow after async detection
MI-119
=> Initial Position Detection

src/frontend/App.vue, src/frontend/pages/CreateEventPage.vue, src/frontend/services/LocationService.js
fixed input and textarea design, fixed safari date parsing, set timeout for geoloaction stuff
fix
=> Fix iOS Bugs

src/backend/controller/UserController.js, src/backend/repositories/EventRepository.js, src/backend/repositories/UserRepository.js
MI-145
Request:
`GET /api/user/<USER_ID>`
Response:
```
Object: {
username: String,
description: String,
hostedEvents: ArrayOf(
id: String,
name: String,
description: String,
time: DateTimeString,
longitude: Float,
latitude: Float
)
}
```
=> Implement User Details Endpoint

src/backend/models/Participation.js, src/backend/models/User.js, src/backend/services/DBService.js
adds participation DB model + minor code cleanup in user DB model
=> Mi 147 event participation model

src/backend/controller/EventController.js, src/backend/repositories/UserRepository.js, src/frontend/components/EventDetails.vue, src/frontend/components/Map.vue, src/frontend/components/TextField.vue, src/frontend/pages/EventDetailPage.vue, src/frontend/services/UserService.js
kleine Änderung an der EventDetailPage um zur UserDetailPage zu gelangen.
=> Event detail page/mi 146

src/frontend/assets/mixins.scss, src/frontend/components/EventListItem.vue, src/frontend/components/HorizontalEventList.vue, src/frontend/components/NotFound.vue, src/frontend/components/UserDetail.vue, src/frontend/index.js, src/frontend/pages/LoginPage.vue, src/frontend/pages/RegistrationPage.vue, src/frontend/pages/UserDetailPage.vue, src/frontend/services/UserService.js
- added mixing for body titles
- added `hideNumbers` option to hide numbers in `HorizontalEventList`
- added user detail page when calling `/user/:uid`
=> added user detail page

src/frontend/components/Map.vue, src/frontend/pages/EventDetailPage.vue, src/frontend/services/MapService.js
add controlPosition prop to map and improve sizing ab eventDetailPage
=> Improve map on EventDetailPage

src/frontend/components/EventDetails.vue, src/frontend/components/UserDetail.vue, src/frontend/pages/HomePage.vue
delete unused link on HomePage
add heading to users events on UserDetailPage
delete coordinate fields on EventDetailPage
remove seconds in time format on EventDetailPage
=> Cleanup und Improvement Vorschläge

src/backend/models/User.js, src/backend/services/JWTService.js
adds homePosition to user model (default object type == null)
adds homePosition to jwt
=> Mi 165 167 home position model jwt

src/frontend/components/HorizontalEventList.vue, src/frontend/components/LocationPicker.vue, src/frontend/components/Map.vue, src/frontend/constants.js, src/frontend/pages/CreateEventPage.vue, src/frontend/pages/EventDetailPage.vue, src/frontend/pages/EventOverviewPage.vue, src/frontend/services/LocationService.js, src/frontend/services/MapService.js
MI-98
Sorry das so viel in einem PR ist :/
Habe immer am ende der files kommentiert was sich geändert hat.
=> Full Location Picker Story

src/frontend/assets/mixins.scss, src/frontend/index.html, src/frontend/index.js, src/frontend/pages/CreateEventPage.vue, src/frontend/pages/MyProfilePage.vue, src/frontend/pages/UserDetailPage.vue, src/frontend/services/EventService.js
MyProfilePage wurde hinzugefügt.
Anmerkungen:
-> Wir sollten bei Komponenten keine Padding/Margin-Werte zum Rand hin setzen, das erschwert das Einfügen in andere Komponenten. 
-> UserDetailPage muss aufgrund der roten Hintergrundfarbe angepasst werden.
=> My profile page

src/backend/controller/UserController.js, src/backend/repositories/UserRepository.js
- adds set home position endpoint with userId from token
- fixes bug in createEvent endpoint (req.body instead of req.query with POST)
=> Mi 166 set home position endpoint

src/backend/services/JWTService.js, src/frontend/services/AuthService.js, src/frontend/services/LocationService.js
- abstract home position in endpoint
- use homeposition in LocationsService
MI-168
=> Use homePosition in LocationsService.getHomePosition

src/frontend/components/HorizontalEventList.vue, src/frontend/components/UserDetail.vue, src/frontend/pages/MyProfilePage.vue, src/frontend/pages/UserDetailPage.vue, src/frontend/services/EventService.js
- conditional text in user details
- reformat code ...
- use component loaders
- minimize mapping
- add click handler for items
- fix fetch
- fix spacings
- improve loading behaviour
MI-97
=> MyProfilePage: fixed missing implementations and bugs

src/frontend/components/LocationPicker.vue, src/frontend/index.html, src/frontend/index.js, src/frontend/pages/CreateEventPage.vue, src/frontend/pages/MyProfilePage.vue, src/frontend/services/EventService.js, src/frontend/services/UserService.js
Add home position picker in MyProfilePage
add mocked method to UserService
add error handling
Beinhaltet PR#60
=> Mi 164/home position picker

src/frontend/App.vue, src/frontend/components/Icon.vue, src/frontend/components/NavBar.vue, src/frontend/pages/EventOverviewPage.vue
- nav bar now shows current state
- cleaned up icon
- fixed overview height bug on firefox
=> added nav-bar state visibility and small fix

src/frontend/components/Button.vue, src/frontend/components/ConfirmationModal.vue, src/frontend/components/EventEditor.vue, src/frontend/components/LocationPicker.vue, src/frontend/pages/EditEventPage.vue, src/frontend/services/EventService.js
=> Mi 207/ Delete Event - connect fe be 

src/backend/app.js, src/backend/controller/UserController.js, src/backend/models/User.js, src/backend/repositories/UserRepository.js
PUT & GET endpoint
`/user/:userId/radius`
Body: ```{
radius: Decimal128
}```
=> Mi 237/radius endpoints

src/backend/models/Push.js, src/backend/repositories/PushRepository.js, src/backend/services/DBService.js
- adds Push DB model
- adds Push Repo with save & delete subscription functions
=> Mi 225/db model push

src/frontend/assets/variables.scss, src/frontend/components/Icon.vue, src/frontend/components/LocationPicker.vue, src/frontend/components/Map.vue, src/frontend/components/RadiusSlider.vue, src/frontend/pages/MyProfilePage.vue, src/frontend/services/MapService.js
- Added slider colors
- Added radius icon
- Added showRadius prop to show radius slider in location picker
- Added radiusCallback that gets called after the map is done loading to draw the radius
- Added ability to initialize map with a new layer that contains the radius
- Added geolocate control to move to the current position of the user
- Added RadiusSlider component
I will work on the map zoom adjustments once the backend saves the radius.
=> Mi 236/location picker radius

src/frontend/components/LocationPicker.vue, src/frontend/components/Map.vue, src/frontend/components/RadiusSlider.vue, src/frontend/pages/EventOverviewPage.vue, src/frontend/pages/MyProfilePage.vue, src/frontend/services/LocationService.js, src/frontend/services/UserService.js
- Added radii getter and setter in BE
- Frontend now loads from and saves radii
- Expanded LocationService's toBounds to take radii
- Overview Page zoom level is now relativ to radius
=> Mi 242/save and load radius

src/frontend/App.vue, src/frontend/components/PWANotification.vue, src/frontend/constants.js, src/frontend/services/PWAService.js
- Add pwa notification and should show algorithm
- will be shown on ios in standalone mode and on localhost
- android uses default pwa promt and installation
MI-193
=> PWA Notification

src/backend/controller/UserController.js, src/backend/models/User.js, src/backend/repositories/UserRepository.js
=> Delete User endpoint

src/backend/models/User.js, src/backend/services/DBService.js, src/backend/services/JWTService.js, src/frontend/services/AuthService.js
Add unique index to username and remove username in jwt token
=> Mi 265 mi 268/unique username and jwt adaption

package-lock.json, package.json, src/backend/controller/PushController.js, src/backend/models/PushSubscription.js, src/backend/repositories/PushRepository.js, src/frontend/services/PushService.js
- add fingerprint to push service in fe
- add fingerprint to db model as unique index
- update push repo to include fingerprint
- update push controller endpoints to include fingerprint
after merging unique index userId must be manually dropped in mongoDB!!!
=> Mi 294+295/fe-be-fingerprintjs

src/backend/controller/UserController.js, src/backend/repositories/UserRepository.js
=> Mi 264/edit user endpoint

src/backend/controller/UserController.js, src/frontend/App.vue, src/frontend/assets/variables.scss, src/frontend/index.js, src/frontend/pages/EditEventPage.vue, src/frontend/pages/EditProfilePage.vue, src/frontend/pages/MyProfilePage.vue, src/frontend/pages/RegistrationPage.vue, src/frontend/pages/UserDetailPage.vue, src/frontend/services/AuthService.js, src/frontend/services/UserService.js
Fix unequally styles for bottom buttons, add delete button, connect 2 be, fix warnings
=> Mi 269/delete user button

src/backend/controller/PushController.js, src/backend/repositories/PushRepository.js, src/frontend/pages/MyProfilePage.vue, src/frontend/services/AuthService.js, src/frontend/services/PushService.js
- adds endpoint to get subscription from DB
- adds endpoint to update subscription in DB
- updates hasSubscribed method to check subscription from service worker and from db and updates subscription if necessary
- refactors whole push service to avoid code duplication
- adds handling of notification permission denial, fixes notification slider bug so that slider is turned off if permission was denied
=> Mi 296+297+310/check subscription

src/frontend/pages/EventOverviewPage.vue, src/frontend/pages/MyProfilePage.vue, src/frontend/services/AuthService.js, src/frontend/services/PushService.js
- if user logs out, he is automatically unsubscribed from push (was already implemented)
- if he logs in again, he will be automatically resubscribed from push if he was subscribed before logout
=> Mi 314/reactivate push after login

src/backend/controller/UserController.js, src/frontend/pages/MyProfilePage.vue, src/frontend/pages/RegistrationPage.vue
FE: Fehlermeldung für bereits vorhandene Daten wird jetzt individuell für Email und Usernamen angezeigt
BE: Erweiterung des Registration Endpoints + Vermeidung von Double Coding
=> Fix error message on registration page

src/frontend/components/LocationPicker.vue
fix desktop layout for location picker footer and map
MI-301
=> Location Picker Footer Fix
